import React, { createContext, useContext, useState, ReactNode, useCallback } from "react";

export type Lang = "en" | "th";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Landing
    "landing.badge": "Financial planning that feels like a game",
    "landing.title1": "Master Your Money,",
    "landing.title2": "One Level at a Time",
    "landing.subtitle": "Stop stressing about finances. Answer fun questions, unlock levels, and get a real financial plan — no jargon, no spreadsheets, no boring stuff.",
    "landing.cta": "🎮 Start Your Journey — Free",
    "landing.ctaSub": "Takes 5 minutes • No sign-up required",
    "landing.startPlaying": "Start Playing",
    "landing.footer": "FinGame — Making financial planning fun 💚",
    "landing.readyCta": "Ready to level up your finances? 🚀",
    "landing.readyCtaSub": "5 levels. 5 minutes. A real financial plan.",
    "landing.letsGo": "Let's Go!",
    "landing.howItWorks": "How It Works",
    "landing.feature1Title": "Learn by Playing",
    "landing.feature1Desc": "Answer simple questions across 5 levels. Each answer secretly builds your financial plan.",
    "landing.feature2Title": "Real Calculations",
    "landing.feature2Desc": "Behind the fun UI, we run the same math a financial advisor uses. Savings, retirement, inflation — all covered.",
    "landing.feature3Title": "No Jargon, No Stress",
    "landing.feature3Desc": "We speak human. Every question is simple, every answer gives instant feedback. Zero financial jargon.",
    "landing.step1": "Start with the basics — how you feel about money",
    "landing.step2": "Tell us about your income and expenses",
    "landing.step3": "Set your savings goals",
    "landing.step4": "Plan for retirement (yes, even if you're 25)",
    "landing.step5": "Discover your risk profile and investment style",

    // Dashboard
    "dash.yourJourney": "Your Journey",
    "dash.levelsComplete": "levels complete",
    "dash.answers": "answers",
    "dash.viewSnapshot": "📊 View Your Financial Snapshot",
    "dash.actionPlan": "📅 Your Action Plan",
    "dash.complete": "Complete",
    "dash.resetProgress": "Reset all progress",
    "dash.resetConfirm": "Reset all progress? This cannot be undone.",

    // Level page
    "level.check": "Check",
    "level.continue": "Continue →",
    "level.complete": "Level Complete! 🎉",
    "level.youCrushed": "You crushed",
    "level.answerShaping": "Your answers are shaping your financial plan.",
    "level.xpEarned": "+50 XP earned",
    "level.continueJourney": "Continue Journey →",
    "level.gotIt": "✅ Got it! Great choice.",

    // Level grouping labels
    "level.income": "💵 Income",
    "level.expenses": "💸 Expenses",
    "level.savings": "🏦 Savings",
    "level.goals": "🎯 Goals",
    "level.behavior": "🧠 Behavior",
    "level.retirement": "🏖️ Retirement",

    // Snapshot
    "snap.title": "Your Financial Snapshot",
    "snap.report": "Your Money Report",
    "snap.basedOn": "Based on your answers across",
    "snap.levels": "levels",
    "snap.xpEarned": "XP earned",
    "snap.monthlySavings": "Monthly Savings",
    "snap.savingsRate": "savings rate",
    "snap.annualSavings": "Annual Savings",
    "snap.moIncome": "/mo income",
    "snap.retirementFund": "Projected Retirement Fund",
    "snap.atAge": "At age",
    "snap.years": "years",
    "snap.inflationAdj": "Inflation-Adjusted Value",
    "snap.todayDollars": "In today's baht",
    "snap.safeSpending": "Safe Monthly Spending in Retirement",
    "snap.riskProfile": "Risk profile",
    "snap.keepPlaying": "Keep playing to refine your plan!",
    "snap.keepPlayingSub": "Complete more levels to get a more accurate snapshot.",
    "snap.backToLevels": "Back to Levels",
    "snap.retirementTarget": "Retirement Target",
    "snap.goalReached": "of goal reached",
    "snap.yearsRetirement": "years of retirement",

    // Calendar
    "cal.actionPlan": "Action Plan",
    "cal.questSchedule": "Your quest schedule",
    "cal.save": "Save",
    "cal.invest": "Invest",
    "cal.spendMax": "Spend max",
    "cal.saveToday": "💰 Save today",
    "cal.spendingLimit": "🛍️ Spending limit",
    "cal.investToday": "📈 Invest today",
    "cal.onTrack": "You are still on track — keep going! 🎮",
    "cal.weekMission": "Week {n} Mission",
    "cal.philosophy": "\"Show them what is possible and doable\" 🎯",
    "cal.backToLevels": "Back to Levels",
    "cal.investmentDay": "📈 Investment Day: +1 step toward retirement",
    "cal.weekCheckpoint": "🎉 Week checkpoint — review your progress",
    "cal.mission1": "🎯 Build momentum — save consistently",
    "cal.mission2": "💪 Stay the course — you're on track",
    "cal.mission3": "🚀 Push harder — almost there",
    "cal.mission4": "🏆 Finish strong — end the month right",
    "cal.mission5": "⭐ Bonus week — every bit counts",

    // Weekdays & Months
    "weekday.mon": "Mon", "weekday.tue": "Tue", "weekday.wed": "Wed",
    "weekday.thu": "Thu", "weekday.fri": "Fri", "weekday.sat": "Sat", "weekday.sun": "Sun",
    "month.0": "January", "month.1": "February", "month.2": "March", "month.3": "April",
    "month.4": "May", "month.5": "June", "month.6": "July", "month.7": "August",
    "month.8": "September", "month.9": "October", "month.10": "November", "month.11": "December",

    // Levels data (legacy)
    "level1.title": "Getting to Know You",
    "level1.desc": "Let's understand your vibe",
    "level2.title": "Money Coming In",
    "level2.desc": "Let's map your income flow",
    "level3.title": "Savings Goals",
    "level3.desc": "Dream big, plan smart",
    "level4.title": "Retirement Planning",
    "level4.desc": "Future you will thank present you",
    "level5.title": "Risk & Mindset",
    "level5.desc": "Discover your investment style",

    // Plan selection
    "plan.selectTitle": "What would you like to plan today?",
    "plan.selectSub": "Pick one — you can always come back for more!",
    "plan.saving.title": "Saving",
    "plan.saving.desc": "Build a savings plan that works for you",
    "plan.goal.title": "Financial Goal",
    "plan.goal.desc": "Plan toward a specific money goal",
    "plan.retirement.title": "Retirement",
    "plan.retirement.desc": "Plan for a comfortable retirement",
    "plan.complete": "Plan Complete! 🎉",
    "plan.completeSub": "Your answers are shaping your financial plan.",
    "plan.viewResults": "📊 View Your Results",
    "plan.backToDash": "Back to Dashboard",
    "plan.nearMax": "You're close to your income limit — that's okay!",
    "plan.enterAmount": "Enter amount",
    "plan.startPlanning": "🗺️ Start Planning",
    "plan.useSlider": "← Use slider instead",
    "plan.enterManual": "Need a higher number? Type it in →",

    // Plan flow questions
    "q.monthly_income": "About how much do you earn per month?",
    "q.monthly_income.help": "Just slide to a rough range — no need to be exact.",
    "q.income_stability": "How stable is your income?",
    "q.income_stability.o1": "💎 Very stable",
    "q.income_stability.o2": "🔀 Varies sometimes",
    "q.income_stability.o3": "🎢 Very unstable",
    "q.avg_income": "On average, how much do you earn per month?",
    "q.avg_income.help": "Your best guess is fine!",
    "q.monthly_expenses": "About how much do you spend each month?",
    "q.monthly_expenses.help": "Rent, food, subscriptions — everything",
    "q.min_expenses": "If really necessary, what is the lowest monthly spending you could manage?",
    "q.min_expenses.help": "Think bare minimum — just the essentials",
    "q.monthly_obligations": "Do you have any monthly obligations?",
    "q.monthly_obligations.help": "Loans, installments, recurring payments",
    "q.monthly_obligations.o1": "🙅 None",
    "q.monthly_obligations.o2": "🤏 A little",
    "q.monthly_obligations.o3": "😰 Quite a lot",
    "q.current_savings": "About how much savings do you currently have?",
    "q.current_savings.o1": "Under 10,000 🌱",
    "q.current_savings.o2": "50,000+ 🌿",
    "q.current_savings.o3": "100,000+ 🌳",
    "q.current_savings.o4": "1,000,000+ 🏔️",
    "q.current_savings.o5": "✏️ Enter manually",
    "q.current_savings_manual": "Enter your current savings",
    "q.saving_goal": "How much would you like to save?",
    "q.saving_goal.help": "Dream big — any number is fine!",
    "q.big_purchase": "Do you plan to buy anything big along the way?",
    "q.big_purchase.o1": "🏠 Home / Condo",
    "q.big_purchase.o2": "🚗 Car",
    "q.big_purchase.o3": "✈️ Travel",
    "q.big_purchase.o4": "Nope, just saving 😌",
    "q.big_purchase_timeline": "When do you plan to buy?",
    "q.big_purchase_timeline.o1": "This year ⚡",
    "q.big_purchase_timeline.o2": "2–3 years 📅",
    "q.big_purchase_timeline.o3": "5+ years 🔮",
    "q.big_purchase_timeline.o4": "Not sure yet 🤷",
    "q.emergency_readiness": "If you had to stop working, how long could you manage?",
    "q.emergency_readiness.o1": "😬 Less than 1 month",
    "q.emergency_readiness.o2": "🤔 1–3 months",
    "q.emergency_readiness.o3": "😎 More than 3 months",
    "q.financial_discipline": "When you plan to save, which sounds most like you?",
    "q.financial_discipline.o1": "📋 I follow my plan",
    "q.financial_discipline.o2": "😅 I try but slip sometimes",
    "q.financial_discipline.o3": "💪 I'm working on it",
    "q.current_age": "How old are you?",
    "q.retirement_age": "When do you want to retire?",
    "q.retirement_age.help": "There's no wrong answer!",
    "q.expected_lifespan": "Roughly, how long do you expect to live?",
    "q.expected_lifespan.help": "Just a rough guess — no pressure!",
    "q.retirement_monthly_expense": "How much would you like to spend per month after retirement?",
    "q.retirement_monthly_expense.help": "Think about your ideal lifestyle",
    "q.retirement_savings": "How much have you saved for retirement so far?",
    "q.retirement_savings.o1": "Under 100,000 🌱",
    "q.retirement_savings.o2": "100,000+ 🌿",
    "q.retirement_savings.o3": "500,000+ 🌳",
    "q.retirement_savings.o4": "1,000,000+ 🏔️",
    "q.retirement_savings.o5": "✏️ Enter manually",
    "q.retirement_savings_manual": "Enter your retirement savings",

    // New differentiated flow questions
    "q.saving_timeline": "How soon do you want to reach your savings goal?",
    "q.saving_timeline.o1": "3 months ⚡",
    "q.saving_timeline.o2": "6 months 📅",
    "q.saving_timeline.o3": "1 year 🎯",
    "q.saving_timeline.o4": "3+ years 🌳",
    "q.goal_priority": "When it comes to hitting your goal, what matters most?",
    "q.goal_priority.o1": "⚡ Speed — reach it ASAP",
    "q.goal_priority.o2": "⚖️ Balance — save and live well",
    "q.goal_priority.o3": "🌊 Flexible — life happens",

    // Validation
    "plan.enterValue": "Please enter a value to continue",

    // Legacy questions
    "q.money_feeling": "How do you feel about money right now?",
    "q.money_feeling.help": "No wrong answers — just be honest!",
    "q.money_feeling.o1": "😰 Stressed",
    "q.money_feeling.o2": "😐 Neutral",
    "q.money_feeling.o3": "😊 Pretty good",
    "q.money_feeling.o4": "🚀 Confident",
    "q.financial_goal": "What's your #1 money goal?",
    "q.financial_goal.o1": "🏠 Buy a home",
    "q.financial_goal.o2": "🏖️ Retire early",
    "q.financial_goal.o3": "💰 Build savings",
    "q.financial_goal.o4": "📊 Invest more",
    "q.saving_habit": "Do you save money regularly?",
    "q.saving_habit.o1": "Every month 💪",
    "q.saving_habit.o2": "Sometimes 🤷",
    "q.saving_habit.o3": "Rarely 😅",
    "q.saving_habit.o4": "Never yet 🙈",
    "q.biggest_expense": "What eats most of your money?",
    "q.biggest_expense.o1": "🏠 Rent/Housing",
    "q.biggest_expense.o2": "🍔 Food & Fun",
    "q.biggest_expense.o3": "🚗 Transport",
    "q.biggest_expense.o4": "🛍️ Shopping",
    "q.emergency_fund": "Could you cover 3 months of expenses?",
    "q.emergency_fund.help": "This is called an 'emergency fund'",
    "q.emergency_fund.o1": "Yes, easily ✅",
    "q.emergency_fund.o2": "Maybe, barely 😬",
    "q.emergency_fund.o3": "Not yet ❌",
    "q.debt_payments": "Any monthly debt payments?",
    "q.debt_payments.help": "Student loans, credit cards, car payments",
    "q.savings_target": "How much would you like to save this year?",
    "q.retirement_lifestyle": "What retirement lifestyle do you imagine?",
    "q.retirement_lifestyle.o1": "🏡 Simple & peaceful",
    "q.retirement_lifestyle.o2": "🌍 Travel the world",
    "q.retirement_lifestyle.o3": "🏢 Start a business",
    "q.retirement_lifestyle.o4": "🎨 Pursue passions",
    "q.risk_tolerance": "If your investment dropped 20%, what would you do?",
    "q.risk_tolerance.help": "This helps us understand your comfort zone",
    "q.risk_tolerance.o1": "😱 Sell everything!",
    "q.risk_tolerance.o2": "😟 Worry but hold",
    "q.risk_tolerance.o3": "😎 Buy more!",
    "q.investment_experience": "Have you invested before?",
    "q.investment_experience.o1": "Never 🌱",
    "q.investment_experience.o2": "A little bit 🌿",
    "q.investment_experience.o3": "Regularly 🌳",
    "q.investment_experience.o4": "I'm a pro 🏔️",
    "q.investment_interest": "What interests you most?",
    "q.investment_interest.o1": "📊 Stocks & ETFs",
    "q.investment_interest.o2": "🏠 Real estate",
    "q.investment_interest.o3": "₿ Crypto",
    "q.investment_interest.o4": "🏦 Safe savings",
  },
  th: {
    // Landing
    "landing.badge": "วางแผนการเงินแบบเล่นเกม",
    "landing.title1": "จัดการเงินของคุณ",
    "landing.title2": "ทีละด่าน",
    "landing.subtitle": "เลิกเครียดเรื่องเงิน ตอบคำถามสนุกๆ ปลดล็อกด่าน แล้วได้แผนการเงินจริงๆ — ไม่มีศัพท์ยาก ไม่มีสเปรดชีต ไม่น่าเบื่อ",
    "landing.cta": "🎮 เริ่มเลย — ฟรี",
    "landing.ctaSub": "ใช้เวลาแค่ 5 นาที • ไม่ต้องสมัคร",
    "landing.startPlaying": "เริ่มเล่น",
    "landing.footer": "FinGame — ทำให้การวางแผนการเงินเป็นเรื่องสนุก 💚",
    "landing.readyCta": "พร้อมอัปเลเวลการเงินของคุณหรือยัง? 🚀",
    "landing.readyCtaSub": "5 ด่าน. 5 นาที. แผนการเงินจริงๆ",
    "landing.letsGo": "ไปเลย!",
    "landing.howItWorks": "ทำงานยังไง",
    "landing.feature1Title": "เรียนรู้ผ่านการเล่น",
    "landing.feature1Desc": "ตอบคำถามง่ายๆ ใน 5 ด่าน แต่ละคำตอบจะสร้างแผนการเงินให้คุณแบบลับๆ",
    "landing.feature2Title": "คำนวณจริงจัง",
    "landing.feature2Desc": "เบื้องหลังความสนุก เราใช้สูตรเดียวกับที่ปรึกษาการเงินใช้ ทั้งเงินออม เกษียณ เงินเฟ้อ ครบหมด",
    "landing.feature3Title": "ไม่มีศัพท์ยาก ไม่เครียด",
    "landing.feature3Desc": "เราพูดภาษาคน ทุกคำถามเข้าใจง่าย ทุกคำตอบได้ฟีดแบ็คทันที ไม่มีศัพท์การเงิน",
    "landing.step1": "เริ่มจากพื้นฐาน — คุณรู้สึกยังไงกับเงิน",
    "landing.step2": "บอกเราเรื่องรายได้และค่าใช้จ่าย",
    "landing.step3": "ตั้งเป้าหมายการออม",
    "landing.step4": "วางแผนเกษียณ (แม้จะอายุ 25 ก็ทำได้)",
    "landing.step5": "ค้นหาสไตล์การลงทุนของคุณ",

    // Dashboard
    "dash.yourJourney": "การเดินทางของคุณ",
    "dash.levelsComplete": "ด่านสำเร็จ",
    "dash.answers": "คำตอบ",
    "dash.viewSnapshot": "📊 ดูสรุปการเงินของคุณ",
    "dash.actionPlan": "📅 แผนปฏิบัติการ",
    "dash.complete": "สำเร็จ",
    "dash.resetProgress": "รีเซ็ตความก้าวหน้าทั้งหมด",
    "dash.resetConfirm": "รีเซ็ตทั้งหมด? ไม่สามารถย้อนกลับได้",

    // Level page
    "level.check": "เช็ค",
    "level.continue": "ถัดไป →",
    "level.complete": "ผ่านด่าน! 🎉",
    "level.youCrushed": "คุณผ่าน",
    "level.answerShaping": "คำตอบของคุณกำลังสร้างแผนการเงินอยู่",
    "level.xpEarned": "+50 XP ได้แล้ว",
    "level.continueJourney": "ไปต่อเลย →",
    "level.gotIt": "✅ เข้าใจแล้ว เลือกได้ดีมาก",

    // Level grouping labels
    "level.income": "💵 รายได้",
    "level.expenses": "💸 ค่าใช้จ่าย",
    "level.savings": "🏦 เงินออม",
    "level.goals": "🎯 เป้าหมาย",
    "level.behavior": "🧠 พฤติกรรม",
    "level.retirement": "🏖️ เกษียณ",

    // Snapshot
    "snap.title": "สรุปการเงินของคุณ",
    "snap.report": "รายงานการเงิน",
    "snap.basedOn": "จากคำตอบของคุณใน",
    "snap.levels": "ด่าน",
    "snap.xpEarned": "XP ที่ได้",
    "snap.monthlySavings": "เงินออมรายเดือน",
    "snap.savingsRate": "อัตราการออม",
    "snap.annualSavings": "เงินออมรายปี",
    "snap.moIncome": "/เดือน รายได้",
    "snap.retirementFund": "กองทุนเกษียณ (ประมาณการ)",
    "snap.atAge": "ตอนอายุ",
    "snap.years": "ปี",
    "snap.inflationAdj": "มูลค่าหลังปรับเงินเฟ้อ",
    "snap.todayDollars": "เทียบค่าเงินวันนี้",
    "snap.safeSpending": "ค่าใช้จ่ายที่ปลอดภัยต่อเดือนตอนเกษียณ",
    "snap.riskProfile": "ระดับความเสี่ยง",
    "snap.keepPlaying": "เล่นต่อเพื่อปรับแผนให้แม่นขึ้น!",
    "snap.keepPlayingSub": "ผ่านด่านเพิ่มจะได้ภาพรวมที่ชัดเจนขึ้น",
    "snap.backToLevels": "กลับไปด่าน",
    "snap.retirementTarget": "เป้าหมายเกษียณ",
    "snap.goalReached": "ของเป้าหมาย",
    "snap.yearsRetirement": "ปีของการเกษียณ",

    // Calendar
    "cal.actionPlan": "แผนปฏิบัติการ",
    "cal.questSchedule": "ตารางเควสของคุณ",
    "cal.save": "ออม",
    "cal.invest": "ลงทุน",
    "cal.spendMax": "ใช้จ่ายสูงสุด",
    "cal.saveToday": "💰 ออมวันนี้",
    "cal.spendingLimit": "🛍️ วงเงินใช้จ่าย",
    "cal.investToday": "📈 ลงทุนวันนี้",
    "cal.onTrack": "คุณยังอยู่ในแผน — ไปต่อเลย! 🎮",
    "cal.weekMission": "เควสสัปดาห์ที่ {n}",
    "cal.philosophy": "\"บอกสิ่งที่เป็นไปได้และทำได้จริง\" 🎯",
    "cal.backToLevels": "กลับไปด่าน",
    "cal.investmentDay": "📈 วันลงทุน: +1 ก้าวสู่เกษียณ",
    "cal.weekCheckpoint": "🎉 เช็คพอยท์ประจำสัปดาห์ — ทบทวนความก้าวหน้า",
    "cal.mission1": "🎯 สร้างโมเมนตัม — ออมให้สม่ำเสมอ",
    "cal.mission2": "💪 รักษาจังหวะ — คุณทำได้ดีอยู่แล้ว",
    "cal.mission3": "🚀 เร่งอีกนิด — ใกล้เป้าแล้ว",
    "cal.mission4": "🏆 จบเดือนให้สวย — สู้ต่อไป",
    "cal.mission5": "⭐ สัปดาห์โบนัส — ทุกบาททุกสตางค์มีค่า",

    // Weekdays & Months
    "weekday.mon": "จ.", "weekday.tue": "อ.", "weekday.wed": "พ.",
    "weekday.thu": "พฤ.", "weekday.fri": "ศ.", "weekday.sat": "ส.", "weekday.sun": "อา.",
    "month.0": "มกราคม", "month.1": "กุมภาพันธ์", "month.2": "มีนาคม", "month.3": "เมษายน",
    "month.4": "พฤษภาคม", "month.5": "มิถุนายน", "month.6": "กรกฎาคม", "month.7": "สิงหาคม",
    "month.8": "กันยายน", "month.9": "ตุลาคม", "month.10": "พฤศจิกายน", "month.11": "ธันวาคม",

    // Levels data (legacy)
    "level1.title": "ทำความรู้จักกัน",
    "level1.desc": "มาเข้าใจสไตล์ของคุณ",
    "level2.title": "เงินเข้า",
    "level2.desc": "มาดูรายได้ของคุณ",
    "level3.title": "เป้าหมายการออม",
    "level3.desc": "ฝันให้ใหญ่ วางแผนให้ฉลาด",
    "level4.title": "วางแผนเกษียณ",
    "level4.desc": "ตัวคุณในอนาคตจะขอบคุณ",
    "level5.title": "ความเสี่ยงและแนวคิด",
    "level5.desc": "ค้นพบสไตล์การลงทุนของคุณ",

    // Plan selection
    "plan.selectTitle": "วันนี้คุณอยากวางแผนเรื่องอะไร?",
    "plan.selectSub": "เลือกได้เลย — กลับมาทำอันอื่นทีหลังได้!",
    "plan.saving.title": "การออมเงิน",
    "plan.saving.desc": "สร้างแผนออมเงินที่เหมาะกับคุณ",
    "plan.goal.title": "เป้าหมายการเงิน",
    "plan.goal.desc": "วางแผนไปสู่เป้าหมายทางการเงินที่ชัดเจน",
    "plan.retirement.title": "เกษียณ",
    "plan.retirement.desc": "วางแผนเกษียณอย่างสบายใจ",
    "plan.complete": "วางแผนเสร็จแล้ว! 🎉",
    "plan.completeSub": "คำตอบของคุณกำลังสร้างแผนการเงินอยู่",
    "plan.viewResults": "📊 ดูผลลัพธ์",
    "plan.backToDash": "กลับไปหน้าหลัก",
    "plan.nearMax": "ใกล้ถึงขีดจำกัดรายได้แล้ว — ไม่เป็นไรนะ!",
    "plan.enterAmount": "ใส่จำนวนเงิน",
    "plan.startPlanning": "🗺️ เริ่มวางแผน",
    "plan.useSlider": "← ใช้สไลเดอร์แทน",
    "plan.enterManual": "ตัวเลขเยอะกว่านี้? พิมพ์เลย →",

    // Plan flow questions
    "q.monthly_income": "รายได้ต่อเดือนของคุณประมาณเท่าไหร่?",
    "q.monthly_income.help": "เลื่อนไปช่วงที่ใกล้เคียงก็ได้ ไม่ต้องเป๊ะ",
    "q.income_stability": "รายได้ของคุณมั่นคงแค่ไหน?",
    "q.income_stability.o1": "💎 มั่นคงมาก",
    "q.income_stability.o2": "🔀 บางเดือนไม่เท่ากัน",
    "q.income_stability.o3": "🎢 ขึ้นลงมาก",
    "q.avg_income": "โดยเฉลี่ย เดือนหนึ่งรายได้ประมาณเท่าไหร่?",
    "q.avg_income.help": "เดาคร่าว ๆ ก็ได้!",
    "q.monthly_expenses": "ปกติคุณใช้จ่ายเดือนละประมาณเท่าไหร่?",
    "q.monthly_expenses.help": "ค่าเช่า อาหาร สมัครบริการ — ทุกอย่าง",
    "q.min_expenses": "ถ้าจำเป็นจริง ๆ คุณคิดว่าสามารถลดค่าใช้จ่ายเหลือประมาณเท่าไหร่ต่อเดือนได้?",
    "q.min_expenses.help": "คิดแค่ปัจจัยพื้นฐาน — สิ่งจำเป็นเท่านั้น",
    "q.monthly_obligations": "ตอนนี้คุณมีภาระผ่อนที่ต้องจ่ายทุกเดือนไหม?",
    "q.monthly_obligations.help": "สินเชื่อ ผ่อนของ ค่างวดต่าง ๆ",
    "q.monthly_obligations.o1": "🙅 ไม่มี",
    "q.monthly_obligations.o2": "🤏 มีนิดหน่อย",
    "q.monthly_obligations.o3": "😰 มีค่อนข้างเยอะ",
    "q.current_savings": "ตอนนี้คุณมีเงินเก็บประมาณเท่าไหร่?",
    "q.current_savings.o1": "ต่ำกว่า 10,000 🌱",
    "q.current_savings.o2": "50,000+ 🌿",
    "q.current_savings.o3": "100,000+ 🌳",
    "q.current_savings.o4": "1,000,000+ 🏔️",
    "q.current_savings.o5": "✏️ ใส่ตัวเลขเอง",
    "q.current_savings_manual": "ใส่จำนวนเงินเก็บปัจจุบัน",
    "q.saving_goal": "คุณอยากเก็บเงินให้ได้เท่าไหร่?",
    "q.saving_goal.help": "ฝันให้ใหญ่ได้เลย — ตัวเลขไหนก็ได้!",
    "q.big_purchase": "ระหว่างทางนี้ มีแผนจะซื้อของชิ้นใหญ่ไหม?",
    "q.big_purchase.o1": "🏠 บ้าน / คอนโด",
    "q.big_purchase.o2": "🚗 รถ",
    "q.big_purchase.o3": "✈️ เที่ยว",
    "q.big_purchase.o4": "ไม่มี แค่อยากเก็บเงิน 😌",
    "q.big_purchase_timeline": "อยากซื้อประมาณเมื่อไหร่?",
    "q.big_purchase_timeline.o1": "ปีนี้ ⚡",
    "q.big_purchase_timeline.o2": "2–3 ปี 📅",
    "q.big_purchase_timeline.o3": "5 ปีขึ้นไป 🔮",
    "q.big_purchase_timeline.o4": "ยังไม่แน่ใจ 🤷",
    "q.emergency_readiness": "ถ้าต้องหยุดทำงานกะทันหัน คุณอยู่ได้กี่เดือน?",
    "q.emergency_readiness.o1": "😬 ไม่ถึง 1 เดือน",
    "q.emergency_readiness.o2": "🤔 1–3 เดือน",
    "q.emergency_readiness.o3": "😎 มากกว่า 3 เดือน",
    "q.financial_discipline": "เวลาตั้งใจเก็บเงิน คุณคิดว่าตัวเองเป็นคนแบบไหน?",
    "q.financial_discipline.o1": "📋 ทำได้ตามแผน",
    "q.financial_discipline.o2": "😅 ตั้งใจ แต่หลุดบ้าง",
    "q.financial_discipline.o3": "💪 กำลังพยายาม",
    "q.current_age": "คุณอายุเท่าไหร่?",
    "q.retirement_age": "อยากเกษียณตอนอายุเท่าไหร่?",
    "q.retirement_age.help": "ไม่มีคำตอบผิดเลยนะ!",
    "q.expected_lifespan": "คร่าว ๆ คุณคิดว่าจะอายุประมาณกี่ปี?",
    "q.expected_lifespan.help": "เดาคร่าว ๆ ก็ได้ ไม่ต้องกดดัน!",
    "q.retirement_monthly_expense": "หลังเกษียณ อยากใช้เงินเดือนละเท่าไหร่?",
    "q.retirement_monthly_expense.help": "ลองคิดถึงไลฟ์สไตล์ที่อยากได้",
    "q.retirement_savings": "ตอนนี้มีเงินออมเพื่อเกษียณเท่าไหร่?",
    "q.retirement_savings.o1": "ต่ำกว่า 100,000 🌱",
    "q.retirement_savings.o2": "100,000+ 🌿",
    "q.retirement_savings.o3": "500,000+ 🌳",
    "q.retirement_savings.o4": "1,000,000+ 🏔️",
    "q.retirement_savings.o5": "✏️ ใส่ตัวเลขเอง",
    "q.retirement_savings_manual": "ใส่จำนวนเงินออมเพื่อเกษียณ",

    // New differentiated flow questions
    "q.saving_timeline": "อยากถึงเป้าหมายการออมภายในกี่เดือน?",
    "q.saving_timeline.o1": "3 เดือน ⚡",
    "q.saving_timeline.o2": "6 เดือน 📅",
    "q.saving_timeline.o3": "1 ปี 🎯",
    "q.saving_timeline.o4": "3 ปีขึ้นไป 🌳",
    "q.goal_priority": "ในการไปถึงเป้าหมาย อะไรสำคัญที่สุดสำหรับคุณ?",
    "q.goal_priority.o1": "⚡ เร็ว — ถึงเป้าเร็วที่สุด",
    "q.goal_priority.o2": "⚖️ สมดุล — ออมและใช้ชีวิตได้",
    "q.goal_priority.o3": "🌊 ยืดหยุ่น — ชีวิตมีเรื่องไม่คาดฝัน",

    // Validation
    "plan.enterValue": "กรุณาใส่จำนวนเพื่อดำเนินการต่อ",

    // Legacy questions
    "q.money_feeling": "ตอนนี้คุณรู้สึกยังไงกับเรื่องเงิน?",
    "q.money_feeling.help": "ไม่มีคำตอบผิด — ตอบตามจริงได้เลย!",
    "q.money_feeling.o1": "😰 เครียด",
    "q.money_feeling.o2": "😐 เฉยๆ",
    "q.money_feeling.o3": "😊 ค่อนข้างดี",
    "q.money_feeling.o4": "🚀 มั่นใจมาก",
    "q.financial_goal": "เป้าหมายการเงินอันดับ 1 ของคุณคือ?",
    "q.financial_goal.o1": "🏠 ซื้อบ้าน",
    "q.financial_goal.o2": "🏖️ เกษียณเร็ว",
    "q.financial_goal.o3": "💰 เก็บเงินให้มากขึ้น",
    "q.financial_goal.o4": "📊 ลงทุนเพิ่ม",
    "q.saving_habit": "คุณออมเงินเป็นประจำไหม?",
    "q.saving_habit.o1": "ทุกเดือน 💪",
    "q.saving_habit.o2": "บางที 🤷",
    "q.saving_habit.o3": "นานๆ ที 😅",
    "q.saving_habit.o4": "ยังไม่เคย 🙈",
    "q.biggest_expense": "อะไรกินเงินคุณมากที่สุด?",
    "q.biggest_expense.o1": "🏠 ค่าเช่า/ที่อยู่",
    "q.biggest_expense.o2": "🍔 อาหารและสังสรรค์",
    "q.biggest_expense.o3": "🚗 ค่าเดินทาง",
    "q.biggest_expense.o4": "🛍️ ช้อปปิ้ง",
    "q.emergency_fund": "ถ้าต้องจ่ายค่าใช้จ่าย 3 เดือน ไหวไหม?",
    "q.emergency_fund.help": "นี่คือสิ่งที่เรียกว่า 'เงินสำรองฉุกเฉิน'",
    "q.emergency_fund.o1": "ไหวสบาย ✅",
    "q.emergency_fund.o2": "อาจจะพอได้ 😬",
    "q.emergency_fund.o3": "ยังไม่ไหว ❌",
    "q.debt_payments": "มีหนี้ที่ต้องจ่ายรายเดือนไหม?",
    "q.debt_payments.help": "สินเชื่อ บัตรเครดิต ผ่อนรถ",
    "q.savings_target": "ปีนี้อยากเก็บเงินได้เท่าไหร่?",
    "q.retirement_lifestyle": "จินตนาการชีวิตเกษียณแบบไหน?",
    "q.retirement_lifestyle.o1": "🏡 เรียบง่าย สงบสุข",
    "q.retirement_lifestyle.o2": "🌍 เที่ยวรอบโลก",
    "q.retirement_lifestyle.o3": "🏢 เปิดธุรกิจ",
    "q.retirement_lifestyle.o4": "🎨 ทำตามความฝัน",
    "q.risk_tolerance": "ถ้าเงินลงทุนลดลง 20% คุณจะทำยังไง?",
    "q.risk_tolerance.help": "เราอยากเข้าใจความสบายใจของคุณ",
    "q.risk_tolerance.o1": "😱 ขายหมด!",
    "q.risk_tolerance.o2": "😟 กังวลแต่ถือต่อ",
    "q.risk_tolerance.o3": "😎 ซื้อเพิ่ม!",
    "q.investment_experience": "เคยลงทุนมาก่อนไหม?",
    "q.investment_experience.o1": "ไม่เคย 🌱",
    "q.investment_experience.o2": "นิดหน่อย 🌿",
    "q.investment_experience.o3": "ลงทุนเป็นประจำ 🌳",
    "q.investment_experience.o4": "เป็นโปรแล้ว 🏔️",
    "q.investment_interest": "สนใจอะไรมากที่สุด?",
    "q.investment_interest.o1": "📊 หุ้นและ ETF",
    "q.investment_interest.o2": "🏠 อสังหาริมทรัพย์",
    "q.investment_interest.o3": "₿ คริปโต",
    "q.investment_interest.o4": "🏦 เงินฝากปลอดภัย",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("fingame-lang");
    return (saved === "th" ? "th" : "en") as Lang;
  });

  const handleSetLang = useCallback((newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem("fingame-lang", newLang);
  }, []);

  const t = useCallback((key: string) => {
    return translations[lang][key] || translations.en[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
